version: '3'
services: 
  postgres:
    image: postgres
    environment:
      - POSTGRES_DB=myAssignment
      - POSTGRES_USER=myAssignment
      - POSTGRES_PASSWORD=password
  emsservice:
    image: mdg786/emsservice:latest
    depends_on:
      - postgres
    ports:
      - 8080:9080
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_USER=myAssignment
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=myAssignment
      - DATABASE_PORT=5432